window.esdocSearchIndex = [
  [
    "wishlist/app/models/actions/abstractactioner.js~abstractactioner",
    "class/app/models/actions/abstractActioner.js~AbstractActioner.html",
    "<span>AbstractActioner</span> <span class=\"search-result-import-path\">wishlist/app/models/actions/abstractActioner.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/addwish/addwish.js~addwish",
    "class/app/components/addWish/addWish.js~AddWish.html",
    "<span>AddWish</span> <span class=\"search-result-import-path\">wishlist/app/components/addWish/addWish.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/addwishlist/addwishlist.js~addwishlist",
    "class/app/components/addWishlist/addWishlist.js~AddWishlist.html",
    "<span>AddWishlist</span> <span class=\"search-result-import-path\">wishlist/app/components/addWishlist/addWishlist.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/buttons/addwishlistbutton.js~addwishlistbutton",
    "class/app/components/buttons/addWishlistButton.js~AddWishlistButton.html",
    "<span>AddWishlistButton</span> <span class=\"search-result-import-path\">wishlist/app/components/buttons/addWishlistButton.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/app/app.js~app",
    "class/app/components/app/app.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">wishlist/app/components/app/app.js</span>",
    "class"
  ],
  [
    "wishlist/app/stores/app/appstore.js~appstore",
    "variable/index.html#static-variable-AppStore",
    "<span>AppStore</span> <span class=\"search-result-import-path\">wishlist/app/stores/app/appStore.js</span>",
    "variable"
  ],
  [
    "wishlist/app/components/authentication/authentication.js~authentication",
    "class/app/components/authentication/authentication.js~Authentication.html",
    "<span>Authentication</span> <span class=\"search-result-import-path\">wishlist/app/components/authentication/authentication.js</span>",
    "class"
  ],
  [
    "wishlist/app/models/cookiemanager/cookiemanager.js~cookiemanager",
    "class/app/models/cookieManager/cookieManager.js~CookieManager.html",
    "<span>CookieManager</span> <span class=\"search-result-import-path\">wishlist/app/models/cookieManager/cookieManager.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/home/home.js~home",
    "class/app/components/home/home.js~Home.html",
    "<span>Home</span> <span class=\"search-result-import-path\">wishlist/app/components/home/home.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/footer/lovelyfooter.js~lovelyfooter",
    "class/app/components/footer/lovelyFooter.js~LovelyFooter.html",
    "<span>LovelyFooter</span> <span class=\"search-result-import-path\">wishlist/app/components/footer/lovelyFooter.js</span>",
    "class"
  ],
  [
    "wishlist/app/app.routes.js~router",
    "class/app/app.routes.js~Router.html",
    "<span>Router</span> <span class=\"search-result-import-path\">wishlist/app/app.routes.js</span>",
    "class"
  ],
  [
    "wishlist/app/models/actions/wishlistactioner.js~types",
    "variable/index.html#static-variable-TYPES",
    "<span>TYPES</span> <span class=\"search-result-import-path\">wishlist/app/models/actions/wishlistActioner.js</span>",
    "variable"
  ],
  [
    "wishlist/app/components/wish/wish.js~wish",
    "class/app/components/wish/wish.js~Wish.html",
    "<span>Wish</span> <span class=\"search-result-import-path\">wishlist/app/components/wish/wish.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/wishlist/wishlist.js~wishlist",
    "class/app/components/wishlist/wishlist.js~Wishlist.html",
    "<span>Wishlist</span> <span class=\"search-result-import-path\">wishlist/app/components/wishlist/wishlist.js</span>",
    "class"
  ],
  [
    "wishlist/app/models/actions/wishlistactioner.js~wishlistactioner",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html",
    "<span>WishlistActioner</span> <span class=\"search-result-import-path\">wishlist/app/models/actions/wishlistActioner.js</span>",
    "class"
  ],
  [
    "wishlist/app/models/wishlistapi/wishlistapi.js~wishlistapi",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html",
    "<span>WishlistApi</span> <span class=\"search-result-import-path\">wishlist/app/models/wishlistApi/wishlistApi.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/wishlist/wishlistdetailed.js~wishlistdetailed",
    "class/app/components/wishlist/wishlistDetailed.js~WishlistDetailed.html",
    "<span>WishlistDetailed</span> <span class=\"search-result-import-path\">wishlist/app/components/wishlist/wishlistDetailed.js</span>",
    "class"
  ],
  [
    "wishlist/app/components/grid/wishlistgrid.js~wishlistgrid",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html",
    "<span>WishlistGrid</span> <span class=\"search-result-import-path\">wishlist/app/components/grid/wishlistGrid.js</span>",
    "class"
  ],
  [
    "wishlist/app/reducers/wishlist/wishlistreducer.js~wishlistsreducer",
    "function/index.html#static-function-WishlistsReducer",
    "<span>WishlistsReducer</span> <span class=\"search-result-import-path\">wishlist/app/reducers/wishlist/wishlistReducer.js</span>",
    "function"
  ],
  [
    "wishlist/app/app.routes.js~router",
    "variable/index.html#static-variable-router",
    "<span>router</span> <span class=\"search-result-import-path\">wishlist/app/app.routes.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "app/app.js",
    "file/app/app.js.html",
    "app/app.js",
    "file"
  ],
  [
    "app/app.routes.js",
    "file/app/app.routes.js.html",
    "app/app.routes.js",
    "file"
  ],
  [
    "app/app.routes.js~router#constructor",
    "class/app/app.routes.js~Router.html#instance-constructor-constructor",
    "app/app.routes.js~Router#constructor",
    "method"
  ],
  [
    "app/components/addwish/addwish.js",
    "file/app/components/addWish/addWish.js.html",
    "app/components/addWish/addWish.js",
    "file"
  ],
  [
    "app/components/addwish/addwish.js~addwish#constructor",
    "class/app/components/addWish/addWish.js~AddWish.html#instance-constructor-constructor",
    "app/components/addWish/addWish.js~AddWish#constructor",
    "method"
  ],
  [
    "app/components/addwish/addwish.js~addwish#render",
    "class/app/components/addWish/addWish.js~AddWish.html#instance-method-render",
    "app/components/addWish/addWish.js~AddWish#render",
    "method"
  ],
  [
    "app/components/addwish/addwish.js~addwish#state",
    "class/app/components/addWish/addWish.js~AddWish.html#instance-member-state",
    "app/components/addWish/addWish.js~AddWish#state",
    "member"
  ],
  [
    "app/components/addwishlist/addwishlist.js",
    "file/app/components/addWishlist/addWishlist.js.html",
    "app/components/addWishlist/addWishlist.js",
    "file"
  ],
  [
    "app/components/addwishlist/addwishlist.js~addwishlist#constructor",
    "class/app/components/addWishlist/addWishlist.js~AddWishlist.html#instance-constructor-constructor",
    "app/components/addWishlist/addWishlist.js~AddWishlist#constructor",
    "method"
  ],
  [
    "app/components/addwishlist/addwishlist.js~addwishlist#render",
    "class/app/components/addWishlist/addWishlist.js~AddWishlist.html#instance-method-render",
    "app/components/addWishlist/addWishlist.js~AddWishlist#render",
    "method"
  ],
  [
    "app/components/addwishlist/addwishlist.js~addwishlist#state",
    "class/app/components/addWishlist/addWishlist.js~AddWishlist.html#instance-member-state",
    "app/components/addWishlist/addWishlist.js~AddWishlist#state",
    "member"
  ],
  [
    "app/components/app/app.js",
    "file/app/components/app/app.js.html",
    "app/components/app/app.js",
    "file"
  ],
  [
    "app/components/app/app.js~app#constructor",
    "class/app/components/app/app.js~App.html#instance-constructor-constructor",
    "app/components/app/app.js~App#constructor",
    "method"
  ],
  [
    "app/components/app/app.js~app#getchildcontext",
    "class/app/components/app/app.js~App.html#instance-method-getChildContext",
    "app/components/app/app.js~App#getChildContext",
    "method"
  ],
  [
    "app/components/app/app.js~app#render",
    "class/app/components/app/app.js~App.html#instance-method-render",
    "app/components/app/app.js~App#render",
    "method"
  ],
  [
    "app/components/app/app.js~app#state",
    "class/app/components/app/app.js~App.html#instance-member-state",
    "app/components/app/app.js~App#state",
    "member"
  ],
  [
    "app/components/app/app.js~app.childcontexttypes",
    "class/app/components/app/app.js~App.html#static-get-childContextTypes",
    "app/components/app/app.js~App.childContextTypes",
    "member"
  ],
  [
    "app/components/authentication/authentication.js",
    "file/app/components/authentication/authentication.js.html",
    "app/components/authentication/authentication.js",
    "file"
  ],
  [
    "app/components/authentication/authentication.js~authentication#componentdidmount",
    "class/app/components/authentication/authentication.js~Authentication.html#instance-method-componentDidMount",
    "app/components/authentication/authentication.js~Authentication#componentDidMount",
    "method"
  ],
  [
    "app/components/authentication/authentication.js~authentication#constructor",
    "class/app/components/authentication/authentication.js~Authentication.html#instance-constructor-constructor",
    "app/components/authentication/authentication.js~Authentication#constructor",
    "method"
  ],
  [
    "app/components/authentication/authentication.js~authentication#render",
    "class/app/components/authentication/authentication.js~Authentication.html#instance-method-render",
    "app/components/authentication/authentication.js~Authentication#render",
    "method"
  ],
  [
    "app/components/authentication/authentication.js~authentication#state",
    "class/app/components/authentication/authentication.js~Authentication.html#instance-member-state",
    "app/components/authentication/authentication.js~Authentication#state",
    "member"
  ],
  [
    "app/components/buttons/addwishlistbutton.js",
    "file/app/components/buttons/addWishlistButton.js.html",
    "app/components/buttons/addWishlistButton.js",
    "file"
  ],
  [
    "app/components/buttons/addwishlistbutton.js~addwishlistbutton#constructor",
    "class/app/components/buttons/addWishlistButton.js~AddWishlistButton.html#instance-constructor-constructor",
    "app/components/buttons/addWishlistButton.js~AddWishlistButton#constructor",
    "method"
  ],
  [
    "app/components/buttons/addwishlistbutton.js~addwishlistbutton#getchildcontext",
    "class/app/components/buttons/addWishlistButton.js~AddWishlistButton.html#instance-method-getChildContext",
    "app/components/buttons/addWishlistButton.js~AddWishlistButton#getChildContext",
    "method"
  ],
  [
    "app/components/buttons/addwishlistbutton.js~addwishlistbutton#render",
    "class/app/components/buttons/addWishlistButton.js~AddWishlistButton.html#instance-method-render",
    "app/components/buttons/addWishlistButton.js~AddWishlistButton#render",
    "method"
  ],
  [
    "app/components/buttons/addwishlistbutton.js~addwishlistbutton#state",
    "class/app/components/buttons/addWishlistButton.js~AddWishlistButton.html#instance-member-state",
    "app/components/buttons/addWishlistButton.js~AddWishlistButton#state",
    "member"
  ],
  [
    "app/components/buttons/addwishlistbutton.js~addwishlistbutton.childcontexttypes",
    "class/app/components/buttons/addWishlistButton.js~AddWishlistButton.html#static-get-childContextTypes",
    "app/components/buttons/addWishlistButton.js~AddWishlistButton.childContextTypes",
    "member"
  ],
  [
    "app/components/footer/lovelyfooter.js",
    "file/app/components/footer/lovelyFooter.js.html",
    "app/components/footer/lovelyFooter.js",
    "file"
  ],
  [
    "app/components/footer/lovelyfooter.js~lovelyfooter#constructor",
    "class/app/components/footer/lovelyFooter.js~LovelyFooter.html#instance-constructor-constructor",
    "app/components/footer/lovelyFooter.js~LovelyFooter#constructor",
    "method"
  ],
  [
    "app/components/footer/lovelyfooter.js~lovelyfooter#getchildcontext",
    "class/app/components/footer/lovelyFooter.js~LovelyFooter.html#instance-method-getChildContext",
    "app/components/footer/lovelyFooter.js~LovelyFooter#getChildContext",
    "method"
  ],
  [
    "app/components/footer/lovelyfooter.js~lovelyfooter#render",
    "class/app/components/footer/lovelyFooter.js~LovelyFooter.html#instance-method-render",
    "app/components/footer/lovelyFooter.js~LovelyFooter#render",
    "method"
  ],
  [
    "app/components/footer/lovelyfooter.js~lovelyfooter#state",
    "class/app/components/footer/lovelyFooter.js~LovelyFooter.html#instance-member-state",
    "app/components/footer/lovelyFooter.js~LovelyFooter#state",
    "member"
  ],
  [
    "app/components/footer/lovelyfooter.js~lovelyfooter.childcontexttypes",
    "class/app/components/footer/lovelyFooter.js~LovelyFooter.html#static-get-childContextTypes",
    "app/components/footer/lovelyFooter.js~LovelyFooter.childContextTypes",
    "member"
  ],
  [
    "app/components/grid/wishlistgrid.js",
    "file/app/components/grid/wishlistGrid.js.html",
    "app/components/grid/wishlistGrid.js",
    "file"
  ],
  [
    "app/components/grid/wishlistgrid.js~wishlistgrid#constructor",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html#instance-constructor-constructor",
    "app/components/grid/wishlistGrid.js~WishlistGrid#constructor",
    "method"
  ],
  [
    "app/components/grid/wishlistgrid.js~wishlistgrid#generatelayout",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html#instance-method-generateLayout",
    "app/components/grid/wishlistGrid.js~WishlistGrid#generateLayout",
    "method"
  ],
  [
    "app/components/grid/wishlistgrid.js~wishlistgrid#onbreakpointchange",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html#instance-method-onBreakpointChange",
    "app/components/grid/wishlistGrid.js~WishlistGrid#onBreakpointChange",
    "method"
  ],
  [
    "app/components/grid/wishlistgrid.js~wishlistgrid#render",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html#instance-method-render",
    "app/components/grid/wishlistGrid.js~WishlistGrid#render",
    "method"
  ],
  [
    "app/components/grid/wishlistgrid.js~wishlistgrid#state",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html#instance-member-state",
    "app/components/grid/wishlistGrid.js~WishlistGrid#state",
    "member"
  ],
  [
    "app/components/grid/wishlistgrid.js~wishlistgrid.defaultprops",
    "class/app/components/grid/wishlistGrid.js~WishlistGrid.html#static-get-defaultProps",
    "app/components/grid/wishlistGrid.js~WishlistGrid.defaultProps",
    "member"
  ],
  [
    "app/components/home/home.js",
    "file/app/components/home/home.js.html",
    "app/components/home/home.js",
    "file"
  ],
  [
    "app/components/home/home.js~home#componentdidmount",
    "class/app/components/home/home.js~Home.html#instance-method-componentDidMount",
    "app/components/home/home.js~Home#componentDidMount",
    "method"
  ],
  [
    "app/components/home/home.js~home#constructor",
    "class/app/components/home/home.js~Home.html#instance-constructor-constructor",
    "app/components/home/home.js~Home#constructor",
    "method"
  ],
  [
    "app/components/home/home.js~home#getchildcontext",
    "class/app/components/home/home.js~Home.html#instance-method-getChildContext",
    "app/components/home/home.js~Home#getChildContext",
    "method"
  ],
  [
    "app/components/home/home.js~home#render",
    "class/app/components/home/home.js~Home.html#instance-method-render",
    "app/components/home/home.js~Home#render",
    "method"
  ],
  [
    "app/components/home/home.js~home#state",
    "class/app/components/home/home.js~Home.html#instance-member-state",
    "app/components/home/home.js~Home#state",
    "member"
  ],
  [
    "app/components/home/home.js~home.childcontexttypes",
    "class/app/components/home/home.js~Home.html#static-get-childContextTypes",
    "app/components/home/home.js~Home.childContextTypes",
    "member"
  ],
  [
    "app/components/theme/maintheme.js",
    "file/app/components/theme/mainTheme.js.html",
    "app/components/theme/mainTheme.js",
    "file"
  ],
  [
    "app/components/wish/wish.js",
    "file/app/components/wish/wish.js.html",
    "app/components/wish/wish.js",
    "file"
  ],
  [
    "app/components/wish/wish.js~wish#constructor",
    "class/app/components/wish/wish.js~Wish.html#instance-constructor-constructor",
    "app/components/wish/wish.js~Wish#constructor",
    "method"
  ],
  [
    "app/components/wish/wish.js~wish#render",
    "class/app/components/wish/wish.js~Wish.html#instance-method-render",
    "app/components/wish/wish.js~Wish#render",
    "method"
  ],
  [
    "app/components/wish/wish.js~wish#state",
    "class/app/components/wish/wish.js~Wish.html#instance-member-state",
    "app/components/wish/wish.js~Wish#state",
    "member"
  ],
  [
    "app/components/wishlist/wishlist.js",
    "file/app/components/wishlist/wishlist.js.html",
    "app/components/wishlist/wishlist.js",
    "file"
  ],
  [
    "app/components/wishlist/wishlist.js~wishlist#constructor",
    "class/app/components/wishlist/wishlist.js~Wishlist.html#instance-constructor-constructor",
    "app/components/wishlist/wishlist.js~Wishlist#constructor",
    "method"
  ],
  [
    "app/components/wishlist/wishlist.js~wishlist#render",
    "class/app/components/wishlist/wishlist.js~Wishlist.html#instance-method-render",
    "app/components/wishlist/wishlist.js~Wishlist#render",
    "method"
  ],
  [
    "app/components/wishlist/wishlistdetailed.js",
    "file/app/components/wishlist/wishlistDetailed.js.html",
    "app/components/wishlist/wishlistDetailed.js",
    "file"
  ],
  [
    "app/components/wishlist/wishlistdetailed.js~wishlistdetailed#componentdidmount",
    "class/app/components/wishlist/wishlistDetailed.js~WishlistDetailed.html#instance-method-componentDidMount",
    "app/components/wishlist/wishlistDetailed.js~WishlistDetailed#componentDidMount",
    "method"
  ],
  [
    "app/components/wishlist/wishlistdetailed.js~wishlistdetailed#constructor",
    "class/app/components/wishlist/wishlistDetailed.js~WishlistDetailed.html#instance-constructor-constructor",
    "app/components/wishlist/wishlistDetailed.js~WishlistDetailed#constructor",
    "method"
  ],
  [
    "app/components/wishlist/wishlistdetailed.js~wishlistdetailed#render",
    "class/app/components/wishlist/wishlistDetailed.js~WishlistDetailed.html#instance-method-render",
    "app/components/wishlist/wishlistDetailed.js~WishlistDetailed#render",
    "method"
  ],
  [
    "app/components/wishlist/wishlistdetailed.js~wishlistdetailed#state",
    "class/app/components/wishlist/wishlistDetailed.js~WishlistDetailed.html#instance-member-state",
    "app/components/wishlist/wishlistDetailed.js~WishlistDetailed#state",
    "member"
  ],
  [
    "app/models/actions/abstractactioner.js",
    "file/app/models/actions/abstractActioner.js.html",
    "app/models/actions/abstractActioner.js",
    "file"
  ],
  [
    "app/models/actions/wishlistactioner.js",
    "file/app/models/actions/wishlistActioner.js.html",
    "app/models/actions/wishlistActioner.js",
    "file"
  ],
  [
    "app/models/actions/wishlistactioner.js~wishlistactioner.addownedwishlist",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html#static-method-addOwnedWishlist",
    "app/models/actions/wishlistActioner.js~WishlistActioner.addOwnedWishlist",
    "method"
  ],
  [
    "app/models/actions/wishlistactioner.js~wishlistactioner.addwish",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html#static-method-addWish",
    "app/models/actions/wishlistActioner.js~WishlistActioner.addWish",
    "method"
  ],
  [
    "app/models/actions/wishlistactioner.js~wishlistactioner.setguestwishlists",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html#static-method-setGuestWishlists",
    "app/models/actions/wishlistActioner.js~WishlistActioner.setGuestWishlists",
    "method"
  ],
  [
    "app/models/actions/wishlistactioner.js~wishlistactioner.setownedwishlists",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html#static-method-setOwnedWishlists",
    "app/models/actions/wishlistActioner.js~WishlistActioner.setOwnedWishlists",
    "method"
  ],
  [
    "app/models/actions/wishlistactioner.js~wishlistactioner.setuser",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html#static-method-setUser",
    "app/models/actions/wishlistActioner.js~WishlistActioner.setUser",
    "method"
  ],
  [
    "app/models/actions/wishlistactioner.js~wishlistactioner.setwish",
    "class/app/models/actions/wishlistActioner.js~WishlistActioner.html#static-method-setWish",
    "app/models/actions/wishlistActioner.js~WishlistActioner.setWish",
    "method"
  ],
  [
    "app/models/cookiemanager/cookiemanager.js",
    "file/app/models/cookieManager/cookieManager.js.html",
    "app/models/cookieManager/cookieManager.js",
    "file"
  ],
  [
    "app/models/cookiemanager/cookiemanager.js~cookiemanager#constructor",
    "class/app/models/cookieManager/cookieManager.js~CookieManager.html#instance-constructor-constructor",
    "app/models/cookieManager/cookieManager.js~CookieManager#constructor",
    "method"
  ],
  [
    "app/models/cookiemanager/cookiemanager.js~cookiemanager.get",
    "class/app/models/cookieManager/cookieManager.js~CookieManager.html#static-method-get",
    "app/models/cookieManager/cookieManager.js~CookieManager.get",
    "method"
  ],
  [
    "app/models/cookiemanager/cookiemanager.js~cookiemanager.remove",
    "class/app/models/cookieManager/cookieManager.js~CookieManager.html#static-method-remove",
    "app/models/cookieManager/cookieManager.js~CookieManager.remove",
    "method"
  ],
  [
    "app/models/cookiemanager/cookiemanager.js~cookiemanager.save",
    "class/app/models/cookieManager/cookieManager.js~CookieManager.html#static-method-save",
    "app/models/cookieManager/cookieManager.js~CookieManager.save",
    "method"
  ],
  [
    "app/models/cookiemanager/cookiemanager.js~cookiemanager.saveobject",
    "class/app/models/cookieManager/cookieManager.js~CookieManager.html#static-method-saveObject",
    "app/models/cookieManager/cookieManager.js~CookieManager.saveObject",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js",
    "file/app/models/wishlistApi/wishlistApi.js.html",
    "app/models/wishlistApi/wishlistApi.js",
    "file"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.addcomment",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-addComment",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.addComment",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.addproposal",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-addProposal",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.addProposal",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.addwish",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-addWish",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.addWish",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.addwishlist",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-addWishlist",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.addWishlist",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.fetchguestwishlist",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-fetchGuestWishlist",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.fetchGuestWishlist",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.log",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-log",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.log",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.parse",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-parse",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.parse",
    "method"
  ],
  [
    "app/models/wishlistapi/wishlistapi.js~wishlistapi.requestfailed",
    "class/app/models/wishlistApi/wishlistApi.js~WishlistApi.html#static-method-requestFailed",
    "app/models/wishlistApi/wishlistApi.js~WishlistApi.requestFailed",
    "method"
  ],
  [
    "app/reducers/app/appreducer.js",
    "file/app/reducers/app/appReducer.js.html",
    "app/reducers/app/appReducer.js",
    "file"
  ],
  [
    "app/reducers/wishlist/wishlistreducer.js",
    "file/app/reducers/wishlist/wishlistReducer.js.html",
    "app/reducers/wishlist/wishlistReducer.js",
    "file"
  ],
  [
    "app/server/server.js",
    "file/app/server/server.js.html",
    "app/server/server.js",
    "file"
  ],
  [
    "app/stores/app/appstore.js",
    "file/app/stores/app/appStore.js.html",
    "app/stores/app/appStore.js",
    "file"
  ]
]